version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always

  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   user: root
  #   volumes:
  #     - ./dev_db_data:/var/opt/mssql/data
  #   env_file:
  #     - .env.sample
  #   ports:
  #     - 1434:1433
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
  #     interval: 10s
  #     retries: 10
  #     start_period: 10s
  #     timeout: 3s
